Added SignIn Page
Harsh2098/facewatch pull request #1
Opened 2020-03-21 06:28 UTC by SreejaJayan

2020-03-21 07:06 UTC, Harsh2098 requested changes

2020-03-21 07:06 UTC, Harsh2098 commented on app/src/main/res/layout/fragment_login.xml
> +    <com.google.android.material.textfield.TextInputLayout
Need `TextView` right?

2020-03-21 07:06 UTC, Harsh2098 commented on app/build.gradle
> +    implementation 'android.arch.navigation:navigation-fragment-ktx:1.0.0-alpha11'
Why change from stable to alpha?

2020-03-21 07:06 UTC, Harsh2098 commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Where this was needed?

2020-03-21 07:06 UTC, Harsh2098 commented on app/src/main/java/com/hmproductions/facewatch/MainActivity.kt
> +import androidx.appcompat.app.ActionBar
Unused import?

2020-03-24 13:53 UTC, SreejaJayan commented on app/src/main/res/layout/fragment_login.xml
> +    <com.google.android.material.textfield.TextInputLayout
I'll change that completely and add a dialog box that says new user created.

2020-03-24 13:54 UTC, SreejaJayan commented on app/build.gradle
> +    implementation 'android.arch.navigation:navigation-fragment-ktx:1.0.0-alpha11'
I did that coz i thought that will fix an error. But the error was something else. Later I forgot about that.

2020-03-24 13:55 UTC, SreejaJayan commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
I have not idea. I dont even remember adding that. I dont want to remove it coz that might create an error.

2020-03-24 13:55 UTC, SreejaJayan commented on app/src/main/java/com/hmproductions/facewatch/MainActivity.kt
> +import androidx.appcompat.app.ActionBar
Yeah. I'll remove that. Again, dont remember adding that.

2020-03-25 07:18 UTC, Harsh2098 commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
What error will it create?

2020-03-25 07:54 UTC, Harsh2098 approved these changes

2020-03-25 08:04 UTC, merged